### ISSUE TITLE
Check DNS and rDNS resolution

### ISSUE THREAD

**Issue by kmizumar** [cloudera-ps/prereq-checks#41]
Check that DNS resolution is correct. e.g. using tools like `dig`, `nslookup`, or even the one-liner Python snippet that Cloudera Manager / host inspector uses.

Check rDNS as well if possible.

**Comment by kmizumar** [comment]
Where can we get the list of hosts to be checked? Checking the hosts in /etc/hosts doesn't make sense since 1) we don't recommend to use /etc/hosts file for name resolution, 2) it's not certain whether the host listed in /etc/hosts will be used as a cluster node. @jamestyj @jhshin9 @myloginid @manojsundaram

**Comment by jamestyj** [comment]
I would just check the host itself where this script is running on.

On 11 Jul 2017 5:56 am, "Kiyoshi Mizumaru" <notifications@github.com> wrote:

Where can we get the list of hosts to be checked? Checking the hosts in
/etc/hosts doesn't make sense since 1) we don't recommend to use /etc/hosts
file for name resolution, 2) it's not certain whether the host listed in
/etc/hosts will be used as a cluster node. @jamestyj
<https://github.com/jamestyj> @jhshin9 <https://github.com/jhshin9>
@myloginid <https://github.com/myloginid> @manojsundaram
<https://github.com/manojsundaram>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cloudera-ps/prereq-checks/issues/41#issuecomment-314332131>,
or mute the thread

**Comment by kmizumar** [comment]
#62 Check DNS and rDNS resolution for the target host is merged.
